name: flutter_playground_booking_app
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.1.0 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  pin_code_fields: ^8.0.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  sms_autofill: ^2.3.1
  intl:
  flutter_staggered_animations: ^1.1.1
  fluttertoast: ^8.2.4
  pinput: ^4.0.0
  share_plus:
  expandable_text:
  calendar_date_picker2:
  flutter_rating_bar:
  image_picker:
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - lib/presentation/ground_category_screen/models/
  fonts: 
    - family: SF Pro Display
      fonts: 
        - asset: assets/fonts/SFProDisplayBold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplaySemibold.ttf
          weight: 600
    - family: Manrope
      fonts: 
        - asset: assets/fonts/ManropeSemiBold.ttf
          weight: 600
